### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by GoogleCodeExporter** [vanadey/tintwizard#47]
```
What steps will reproduce the problem?
1. Extract
2. Try to execute (i made sure it can be executed)

What is the expected output? What do you see instead?
The expected is the shown window i think? Instead i got a import problem: no 
module named pygtk (it is installed)

What version of the product are you using? On what operating system?
Arch Linux

```

Original issue reported on code.google.com by `denivyru...@gmail.com` on 24 Apr 2014 at 8:03

**Comment by vanadey** [comment]
When the Python interpreter attempts to import modules, it looks for them in three successive locations, defined by the language specification:

1. the working directory
2. `PYTHONPATH` (syntax as for `PATH`).
3. installation-dependent default (e.g. `/usr/lib/python2.7/dist-packages/` for Ubuntu)

Thus the problem is actually one of local system configuration...
